### ISSUE TITLE
[SNCU] Offline dashboards

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#48]
Source  : https://avni.freshdesk.com/a/tickets/1311
This issue was raised via Support tickets mentioned above and requirements are confirmed on email by Salil Arora.

Percentage against the numbers on all 4 dashboard card are to be added as per below logic:

- [x] 1. Current SAM children

Logic: Children aged more than 6 months and up to 5 years having diagnosed with SAM as per the system excluding death and permanently migrated children.
Numerator for percentage calculation: Count of SAM children as per above logic
Denominator for percentage calculation: Total children enrolled excluding death cases, permanently migrated and children above 5 years of age.

- [x] 2. Current MAM Children

Logic: Children aged more than 6 months and up to 5 years having diagnosed with MAM as per the system excluding death and permanently migrated children.
Numerator for percentage calculation: Count of MAM children as per above logic
Denominator for percentage calculation: Total children enrolled excluding death cases, permanently migrated and children above 5 years of age.

- [x] 3. Low birth weight children

Logic: Total children had a birth weight of less than 2.5 kg at the time of birth excluding death and permanently migrated.
Numerator for percentage calculation: Total children had a birth weight of less than 2.5 kg at the time of birth excluding death and permanently migrated.
Denominator for percentage calculation: Total children enrolled excluding death cases, permanently migrated and children above 5 years of age.

- [x] 4. Children who migrated permanently

Logic: Total count of children who have permanently migrated.
Numerator for percentage calculation: Count of children who migrated permanently.
Denominator for percentage calculation: Total children enrolled excluding death cases, permanently migrated and children above 5 years of age.

**Comment by nupoorkhandelwal** [comment]
Due to performance issues some of the above cards were removed from the existing dashboard. Currently we have only following ones -

1. Low Birth weight Children
2. Total SAM Children
3. Total MAM children
4. Children who migrated permanently

**Comment by salilsamanvay** [comment]
Numerator: Permanently migrated child count

Denominator: Total enrolled children who are less than or equal to 5 yrs of age, have to exclude who are program exit and are death

**Comment by vedfordev** [comment]
### Developer Note:

Backup of dashboard query : [Github](https://github.com/avniproject/SNCU/blob/master/dashboard/dashboard.md)

**Comment by BEULAHEVANJALIN** [comment]
#### Total SAM Children (non-exited and non-voided)

**SAM Children (Numerator):**
- [x] Aged more than 6 months and up to 5 years.
- [ ] Excluding children who have died and have permanently migrated. (As the card's title says explicity "non-exited and non-voided", there is no need to explicitly check for children who have died or permanently migrated because the "non-exit" condition already accounts for these checks)
- [x] Diagnosed with SAM as per the child program.

**Total Children Enrolled (Denominator)**
- [ ] Aged more than 6 months and up to 5 years. (But the requirements only give up to 5 years. So should this include people who are less than 6 months old?)
- [ ] Excluding children who have died and have permanently migrated. (same as above)
- [x] Enrolled in the child program
 
---
#### Low birth weight children (Includes non exited and non voided children)
```
SELECT COUNT(*)
FROM (SELECT i.id,
             i.date_of_birth,
             ice.program_exit_date_time
      FROM individual i
               JOIN individual_child_exit ice ON i.id = ice.individual_id
      WHERE EXTRACT(YEAR FROM ice.program_exit_date_time - i.date_of_birth) > 5) AS age_filtered_data;
```
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGhKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f4b0a675324d09d43233940b89647c01e3299a2/image.png)

In cases where there are no children who have exited from the program after 5 or more years, calculating a percentage may not be meaningful because the denominator (the total number of children meeting the condition) is zero. What is the appropriate way to handle situations where there are zero cases for the denominator?

**Comment by Dinesh2019** [comment]
1.if we have the individual 
Numerator for percentage calculation: 1
Denominator for percentage calculation: 0 what will be the answer for this 
2. And in the client app if exit the individual stating as other the card displays the count as 0 but we have to calculate the percentage.
3. What happens if we have the voided scenario

**Comment by salilsamanvay** [comment]
@Dinesh2019 Numerator greator than denominator should not come, if it is coming that is an error, both can be zero, in that case percentage will also show "0%", voided cases are excluded from both numerator and denominator.

**Comment by Dinesh2019** [comment]
getting this error

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRYQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4828dd3c104487f4b46a674e331aed667f01802/Screen%20Recording%202023-10-20%20at%207.04.25%E2%80%AFAM.mov

**Comment by Dinesh2019** [comment]
getting this error

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRYQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4828dd3c104487f4b46a674e331aed667f01802/Screen%20Recording%202023-10-20%20at%207.04.25%E2%80%AFAM.mov

**Comment by Dinesh2019** [comment]
@BEULAHEVANJALIN Having a doubt about the calculation in the Cilent app calculation is based on catchment right?
2. Equal 5 years is not calculated up to 5 years means <= 5 years 
3. If I register a child and enroll in the SAM at the age of 7 months and if the child completes the 6 years at that time the dashboard card count is given as 0 but the percentage shows as NaN


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUplQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1257bb1bc4dc3fa03f6730035bf463e367e0f84a/SNCU%20Dashboard.mov

**Comment by Gojo-Taqi** [comment]
Fixed the offline reports for
- Total SAM children 
- Total MAM children

**Comment by Dinesh2019** [comment]
@Gojo-Taqi @nupoorkhandelwal like SAM and MAM count we have to remove the count of the card if the child exists 5 years 

- [x] if we add the child at 6 and child reaches the age of the 6 years the count is removed from Current SAM children
- [x] Like wise if we enroll the child at 6 and child reaches the age of 6 years the count should be removed as excpeted but actual the count still present in the below mentioned card 
 Low birth weight children and Children who migrated permanently

**Comment by Dinesh2019** [comment]
Test scenario :

1. Register the individual and enroll in the child program with the age of 6 months complete the follow-up as Sam Count should be added in the card of Current SAM children and the percentage should be calculated as sam child/total child enrolled
2. Register the individual and enroll in the child program with the age of 6 months complete the follow-up as MAM Count should be added in the card of Current MAM children and the percentage should be calculated as MAMchild/total child enrolled
3. Register the individual and enroll in the child program with the age of 6 months as weight less than 2.5kg should be added to the card of Low birth weight children  and the percentage should be calculated as Low birth weight children child/total child register
4. Exit the individual from the child program with the age of 6 months as permanently migrated should be added to the card of children who migrated permanently and the percentage should be calculated as Children who migrated permanently child/total child enrolled
5. Exit the individual should remove the count from all the mentioned card 
6. If the child reaches the age of greater than 6 years then the count should be removed from all the mentioned card
7. void the individual should remove the count from all the mentioned cards.

Test Execution :
https://drive.google.com/drive/folders/1F6BqkgqWp3zZNSF_QcuO83orQVb0Kg8V
